---
- name: Create my user
  user:
    name: "{{ user.name }}"
    state: present
    shell: /bin/bash
    groups: "sudo,adm"
    password: "{{ user.password | password_hash('sha512') }}"
    create_home: true

- name: Update apt packages
  apt:
    update_cache: true

- name: Install needed packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - python3.8-venv
    - python3-pip
    - authbind
    - netplan.io
    - htop

- name: Copy folder backend and frontend/build.zip
  copy:
    src: "{{ item }}"
    dest: "{{ careas_apps_dir }}"
    mode: 0777
  loop:
    - "{{ playbook_dir }}/../backend"
    - "{{ playbook_dir }}/../frontend/build.zip"

- name: Install virtual-env and backend requirements
  pip:
    requirements: "{{ careas_apps_dir }}/backend/requeriments.txt"
    virtualenv: "{{ careas_apps_dir }}/pyvenv"
    virtualenv_command: /usr/bin/python3.8 -m venv

- name: Install careas-pip on virtual-env
  pip:
    name: git+https://github.com/eusoubrasileiro/aidbag.git#subdirectory=anm/careas-pip
    virtualenv: "{{ careas_apps_dir }}/pyvenv"
    virtualenv_site_packages: true
    virtualenv_command: /usr/bin/python3.8 -m venv

# copy react-javascript BUILT bundle to frontend
# from windows or any other place it was built to same folder ...
- name: Unpack build, chown dir, 
  shell:
    cmd: |        
      mkdir -p frontend && unzip build.zip -d frontend
      chown -R andre:andre ../careas_apps/*        
    chdir: "{{ careas_apps_dir }}"

# careas_apps running by user andre (better control not root)
# to allow run on port 8000 
# HTTPS and forward will be dealt by https://loophole.cloud/
# so passing access to specified user
- name: Authbind authorize user andre port 8000
  shell: |
    touch /etc/authbind/byport/8000
    chmod 500 /etc/authbind/byport/8000
    chown andre /etc/authbind/byport/8000

- name: Install backend .service
  template:
    src: etc/systemd/system/careas_apps_backend.service
    dest: /etc/systemd/system/


- name: Enable and start flask backend services
  systemd:
    name: "{{ item }}"
    enabled: true
    masked: false
    state: restarted
    daemon_reload: true
    force: true
  loop:
    - careas_apps_backend
