---
- name: Create my user
  user:
    name: "{{ user.name }}"
    state: present
    shell: /bin/bash
    groups: "sudo,adm"
    password: "{{ user.password | password_hash('sha512') }}"
    create_home: true

- name: Update apt packages
  apt:
    update_cache: true

- name: Install needed packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - python3.8-venv
    - python3-pip    
    - netplan.io
    - htop
    # nginx forward requests from frontend to backend
    - nginx 

- name: Create careas_apps folders (if not exist)
  file:    
    path: "{{ careas_apps_dir }}/frontend"
    state: directory
    owner: andre
    group: andre
    mode: "a+rx"
  tags:
    - webserver

# copy react-javascript BUILT bundle to frontend
# from windows or any other place it was built to same folder ...
# nginx needs a+Rx permission to access the contents of the build folder
# otherwise error 404
- name: Syncronize files/folder frontend
  copy:
    src: /home/andre/Projects/careas_apps/frontend/build
    dest: "{{ careas_apps_dir }}/frontend"
    force: true
    owner: andre
    group: andre
    mode: "a+rx"
  tags:
    - webserver

- name: Syncronize files/folder backend
  become: true
  copy:
    src: /home/andre/Projects/careas_apps/backend
    dest: "{{ careas_apps_dir }}"
    force: true
    owner: andre
    group: andre
    mode: "a+rx"
  tags:
    - webserver

- name: Install virtual-env and backend requirements
  pip:
    requirements: "{{ careas_apps_dir }}/backend/requeriments.txt"
    virtualenv: "{{ careas_apps_dir }}/pyvenv"
    virtualenv_command: /usr/bin/python3.8 -m venv
  tags:
    - webserver

- name: Install careas-pip on virtual-env
  pip:
    name: git+https://github.com/eusoubrasileiro/aidbag.git#subdirectory=anm/careas-pip
    virtualenv: "{{ careas_apps_dir }}/pyvenv"
    virtualenv_site_packages: true
    virtualenv_command: /usr/bin/python3.8 -m venv
  tags:
    - webserver
  
# careas_apps running by user andre (better control not root)
# to allow run on port 8000 
# HTTPS and forward will be dealt by https://loophole.cloud/
# so passing access to specified user
- name: Authbind authorize user andre port 8000
  shell: |
    touch /etc/authbind/byport/8000
    chmod 500 /etc/authbind/byport/8000
    chown andre /etc/authbind/byport/8000
  tags:
    - webserver

- name: Install nginx sites-enabled
  template:
    src: etc/nginx/sites-enabled/careas_apps_react.conf
    dest: /etc/nginx/sites-enabled
  tags:
    - webserver

