---

- name: configure careas_apps webserver
  include_tasks: careas_apps.yaml
  tags:
    - always

- name: set-up readonly overlay mount 
  include_tasks: readonly.yaml
  tags:
    - never

- name: mount set-up network storage
  include_tasks: network_storage.yaml
  tags:
    - always