---

- name: configure careas_apps webserver
  include_tasks: careas_apps.yaml
  tags:
    - always
    - webserver

- name: Install *.service files
  template:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item | basename }}"
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - "{{ role_path }}/templates/etc/systemd/system/*.service"
  tags:
    - always
    - services

- name: set-up readonly overlay mount 
  include_tasks: readonly.yaml
  tags:
    - always
    - ro_overlay

- name: mount set-up network storage
  include_tasks: network_storage.yaml
  tags:
    - always

- name: install loophole to tunnel my local webserver to public web
  include_tasks: loophole.yaml
  tags:
    - always

- name: Enable and start flask backend services
  systemd:
    name: "{{ item }}"
    enabled: true
    masked: false
    state: restarted
    daemon_reload: true
    force: true
  loop:
    - careas_apps_backend
    - nginx 
  tags:
    - services
