- name: Install needed packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - ntfs-3g
    - fuse    
    - nfs-kernel-server
  tags:    
    - nfs 

# fstab to add
# /dev/sda1 /mnt/motion ext4 defaults 0 0
# UUID=5D2B1A0447C0214A /mnt/shared ntfs-3g uid=andre,gid=andre,umask=0022 0 2
- name: Mount Motion Ext Usb HDD SDA1 400 GB for MOTION NVR
  ansible.posix.mount:
    path: /mnt/motion
    src: /dev/sda1
    fstype: ext4
    opts: defaults
    state: mounted
  become: true
  tags:    
    - nfs 

# ntfs-3g doesn't support change ownership or whatever since it comes from windows
- name: Mount /mnt/shared with options
  ansible.posix.mount:
    path: /mnt/shared
    src: UUID=5D2B1A0447C0214A
    fstype: ntfs-3g
    state: mounted
  become: true
  tags:    
    - nfs

# /mnt/shared is NTFS-3g so must be accessed as root to rw
# /mnt/motion is mounted by user 1001 (andre is 10001 since 1000 is orangepi)
# hence must access as 1001 to have rw access
- name: Configure NFS exports
  become: yes
  lineinfile:
    path: /etc/exports
    line: "{{ item.line }}"
    insertafter: EOF
    state: present
    regexp: "^{{ item.line }}$"
  loop:
    - { line: "/mnt/shared *(rw,sync,no_root_squash)" }
    - { line: "/mnt/motion *(rw,sync,all_squash,no_subtree_check,anonuid=1001,anongid=1001)" }
  tags:    
    - nfs

- name: restart nfs server
  become: yes
  service:
    name: nfs-server
    state: restarted


# add user/passwd to samba share, workgroup is the domain (default)
# sudo smbpasswd -a andre
# append to /etc/samba/smb.conf
# [shared]
# path = /mnt/shared
# valid users = andre
# read only = no


